# This workflow will do a clean install of node dependencies, minify the website, and deploy it to S3
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS Objects
      run: git lfs fetch --all
    - name: Use Node.js '22.x'
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: npm ci
    - run: npm run build --if-present

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./build/ s3://www.scca-classifier.com --delete
